language: ruby

rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0

matrix:
  allow_failures:
    - rvm: 2.5
    - rvm: jruby-19mode

before_install: umask 0022

gemfile:
  - gemfiles/Gemfile.ci

sudo: false
